name: Terraform ecs apply
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
      - name: Output ECS cluster name
        run: echo "::set-output name=demo-app::$(terraform output demo-app)"
      - name: Output Fargate task definition ARN
        run: echo "::set-output name=task_definition_arn::$(terraform output fargate_task_definition_arn)"
